In [52]:
import numpy as np

In [53]:
x = [10,15,20]

In [54]:
def func1(x):
    x = np.array(x)
    i = np.array(range(1,len(x)+1))
    result = 1/40*np.sum(x**2) + 1 - np.prod(np.cos(x/i))
    
    return result

In [55]:
func1(x)

19.394726589961355

In [56]:
func1([5,8,10])

5.542983917679211

In [57]:
func1([0,0,0]) #minimum w 0,0,0 legitnie wyglada

0.0

In [104]:
func1([40,40,40])

121.19596504031345

In [105]:
func1([-40,-40,-40])

121.19596504031345

In [95]:
def func2(x):
    x = np.array(x)
    n = len(x)
    result_1 = 20 * np.exp(-0.2 * np.sqrt(1/n * np.sum(x**2)))
    result_2 = - np.exp(1/n * np.sum(np.cos(2*np.pi*x))) + 20 + np.e
    print('1:', result_1)
    print('2:', result_2)
    return result_1 + result_2

In [97]:
func2([0,0,0])

1: 20.0
2: 20.0


40.0

In [109]:
n = 2 
x = np.array([0,0])

In [111]:
- np.exp(1/n * np.sum(np.cos(2*np.pi*x)))

-2.718281828459045

In [103]:
np.cos(x)

array([-0.83907153, -0.75968791,  0.40808206])

In [101]:
np.exp(100)

2.6881171418161356e+43

In [59]:
np.sqrt(4)

2.0

In [67]:
np.e

2.718281828459045

In [84]:
- 2

-2

In [89]:
x = np.array(x)
x

array([10, 15, 20])

In [92]:
np.cos(2*x*np.pi)

array([1., 1., 1.])